#!bin/bash
touch /etc/yum.repos.d/MariaDB10.repo
cat > /etc/yum.repos.d/MariaDB10.repo <<EOF
# MariaDB 10.1 CentOS repository list - created 2016-01-18 09:58 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name=MariaDB
baseurl=http://yum.mariadb.org/10.1/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF
yum remove -y mariadb-server mariadb mariadb-libs
yum clean all 
yum -y install MariaDB-server MariaDB-client
systemctl start mariadb
systemctl enable mariadb
mysql_upgrade
